# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0003_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('time_of_purchase', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtest.Games'),
        ),
        migrations.AddField(
            model_name='purchasedgame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtest.CustomUser'),
        ),
    ]
