# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0004_auto_20170125_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedgame',
            old_name='state',
            new_name='score',
        ),
        migrations.AddField(
            model_name='purchasedgame',
            name='playerItems',
            field=models.CharField(default='', max_length=200),
        ),
    ]
