# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0005_auto_20170127_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedgame',
            name='playerItems',
        ),
        migrations.AddField(
            model_name='purchasedgame',
            name='gameState',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
